[2025-03-28T22:00:07.364+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-28T22:00:07.423+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality_monitoring_v3.initialize_database scheduled__2025-03-28T21:40:00+00:00 [queued]>
[2025-03-28T22:00:07.436+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality_monitoring_v3.initialize_database scheduled__2025-03-28T21:40:00+00:00 [queued]>
[2025-03-28T22:00:07.436+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-03-28T22:00:07.456+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): initialize_database> on 2025-03-28 21:40:00+00:00
[2025-03-28T22:00:07.493+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=16649) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-28T22:00:07.496+0000] {standard_task_runner.py:72} INFO - Started process 16674 to run task
[2025-03-28T22:00:07.500+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'air_quality_monitoring_v3', 'initialize_database', 'scheduled__2025-03-28T21:40:00+00:00', '--job-id', '476', '--raw', '--subdir', 'DAGS_FOLDER/data_enriched_predict.py', '--cfg-path', '/tmp/tmp_jq9mia4']
[2025-03-28T22:00:07.503+0000] {standard_task_runner.py:105} INFO - Job 476: Subtask initialize_database
[2025-03-28T22:00:07.710+0000] {task_command.py:467} INFO - Running <TaskInstance: air_quality_monitoring_v3.initialize_database scheduled__2025-03-28T21:40:00+00:00 [running]> on host 04906466de51
[2025-03-28T22:00:07.967+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='air_quality_monitoring_v3' AIRFLOW_CTX_TASK_ID='initialize_database' AIRFLOW_CTX_EXECUTION_DATE='2025-03-28T21:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-28T21:40:00+00:00'
[2025-03-28T22:00:07.968+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-28T22:00:08.179+0000] {base.py:84} INFO - Retrieving connection 'postgres_data'
[2025-03-28T22:00:08.244+0000] {data_enriched_predict.py:73} INFO - Tables créées/réinitialisées avec succès
[2025-03-28T22:00:08.270+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-28T22:00:08.318+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-28T22:00:08.319+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=air_quality_monitoring_v3, task_id=initialize_database, run_id=scheduled__2025-03-28T21:40:00+00:00, execution_date=20250328T214000, start_date=20250328T220007, end_date=20250328T220008
[2025-03-28T22:00:08.356+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-28T22:00:08.424+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-28T22:00:08.427+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
