[2025-03-29T08:20:05.149+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-29T08:20:05.197+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality_monitoring_v3.initialize_database scheduled__2025-03-29T08:00:00+00:00 [queued]>
[2025-03-29T08:20:05.208+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality_monitoring_v3.initialize_database scheduled__2025-03-29T08:00:00+00:00 [queued]>
[2025-03-29T08:20:05.209+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-03-29T08:20:05.227+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): initialize_database> on 2025-03-29 08:00:00+00:00
[2025-03-29T08:20:05.266+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=37814) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-29T08:20:05.256+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'air_quality_monitoring_v3', 'initialize_database', 'scheduled__2025-03-29T08:00:00+00:00', '--job-id', '569', '--raw', '--subdir', 'DAGS_FOLDER/data_enriched_predict.py', '--cfg-path', '/tmp/tmpts3twrsi']
[2025-03-29T08:20:05.268+0000] {standard_task_runner.py:72} INFO - Started process 37839 to run task
[2025-03-29T08:20:05.268+0000] {standard_task_runner.py:105} INFO - Job 569: Subtask initialize_database
[2025-03-29T08:20:05.574+0000] {task_command.py:467} INFO - Running <TaskInstance: air_quality_monitoring_v3.initialize_database scheduled__2025-03-29T08:00:00+00:00 [running]> on host 04906466de51
[2025-03-29T08:20:05.818+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='air_quality_monitoring_v3' AIRFLOW_CTX_TASK_ID='initialize_database' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-29T08:00:00+00:00'
[2025-03-29T08:20:05.820+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-29T08:20:05.917+0000] {base.py:84} INFO - Retrieving connection 'postgres_data'
[2025-03-29T08:20:05.964+0000] {data_enriched_predict.py:73} INFO - Tables créées/réinitialisées avec succès
[2025-03-29T08:20:05.991+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-29T08:20:06.034+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-29T08:20:06.035+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=air_quality_monitoring_v3, task_id=initialize_database, run_id=scheduled__2025-03-29T08:00:00+00:00, execution_date=20250329T080000, start_date=20250329T082005, end_date=20250329T082006
[2025-03-29T08:20:06.090+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-29T08:20:06.146+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-29T08:20:06.149+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
