[2025-03-29T04:00:04.384+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-29T04:00:04.429+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality_monitoring_v3.initialize_database scheduled__2025-03-29T03:40:00+00:00 [queued]>
[2025-03-29T04:00:04.441+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality_monitoring_v3.initialize_database scheduled__2025-03-29T03:40:00+00:00 [queued]>
[2025-03-29T04:00:04.442+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-03-29T04:00:04.456+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): initialize_database> on 2025-03-29 03:40:00+00:00
[2025-03-29T04:00:04.469+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'air_quality_monitoring_v3', 'initialize_database', 'scheduled__2025-03-29T03:40:00+00:00', '--job-id', '530', '--raw', '--subdir', 'DAGS_FOLDER/data_enriched_predict.py', '--cfg-path', '/tmp/tmpeexckegx']
[2025-03-29T04:00:04.471+0000] {standard_task_runner.py:105} INFO - Job 530: Subtask initialize_database
[2025-03-29T04:00:04.472+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=28924) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-29T04:00:04.473+0000] {standard_task_runner.py:72} INFO - Started process 28949 to run task
[2025-03-29T04:00:04.610+0000] {task_command.py:467} INFO - Running <TaskInstance: air_quality_monitoring_v3.initialize_database scheduled__2025-03-29T03:40:00+00:00 [running]> on host 04906466de51
[2025-03-29T04:00:04.794+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='air_quality_monitoring_v3' AIRFLOW_CTX_TASK_ID='initialize_database' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T03:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-29T03:40:00+00:00'
[2025-03-29T04:00:04.795+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-29T04:00:04.858+0000] {base.py:84} INFO - Retrieving connection 'postgres_data'
[2025-03-29T04:00:04.898+0000] {data_enriched_predict.py:73} INFO - Tables créées/réinitialisées avec succès
[2025-03-29T04:00:04.923+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-29T04:00:05.066+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-29T04:00:05.067+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=air_quality_monitoring_v3, task_id=initialize_database, run_id=scheduled__2025-03-29T03:40:00+00:00, execution_date=20250329T034000, start_date=20250329T040004, end_date=20250329T040005
[2025-03-29T04:00:05.090+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-29T04:00:05.146+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-29T04:00:05.148+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
