[2025-03-29T00:40:05.274+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-29T00:40:05.324+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality_monitoring_v3.initialize_database scheduled__2025-03-29T00:20:00+00:00 [queued]>
[2025-03-29T00:40:05.335+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality_monitoring_v3.initialize_database scheduled__2025-03-29T00:20:00+00:00 [queued]>
[2025-03-29T00:40:05.336+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-03-29T00:40:05.356+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): initialize_database> on 2025-03-29 00:20:00+00:00
[2025-03-29T00:40:05.393+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=22083) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-29T00:40:05.388+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'air_quality_monitoring_v3', 'initialize_database', 'scheduled__2025-03-29T00:20:00+00:00', '--job-id', '500', '--raw', '--subdir', 'DAGS_FOLDER/data_enriched_predict.py', '--cfg-path', '/tmp/tmp9m1zoo16']
[2025-03-29T00:40:05.397+0000] {standard_task_runner.py:72} INFO - Started process 22108 to run task
[2025-03-29T00:40:05.397+0000] {standard_task_runner.py:105} INFO - Job 500: Subtask initialize_database
[2025-03-29T00:40:05.610+0000] {task_command.py:467} INFO - Running <TaskInstance: air_quality_monitoring_v3.initialize_database scheduled__2025-03-29T00:20:00+00:00 [running]> on host 04906466de51
[2025-03-29T00:40:05.969+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='air_quality_monitoring_v3' AIRFLOW_CTX_TASK_ID='initialize_database' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T00:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-29T00:20:00+00:00'
[2025-03-29T00:40:05.972+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-29T00:40:06.055+0000] {base.py:84} INFO - Retrieving connection 'postgres_data'
[2025-03-29T00:40:06.107+0000] {data_enriched_predict.py:73} INFO - Tables créées/réinitialisées avec succès
[2025-03-29T00:40:06.137+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-29T00:40:06.178+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-29T00:40:06.178+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=air_quality_monitoring_v3, task_id=initialize_database, run_id=scheduled__2025-03-29T00:20:00+00:00, execution_date=20250329T002000, start_date=20250329T004005, end_date=20250329T004006
[2025-03-29T00:40:06.218+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-29T00:40:06.277+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-29T00:40:06.279+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
